=== joseluissol/cursoJava/XML/src/es/coritel/java/xsd/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="products">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="product" maxOccurs="unbounded">
				<xs:complexType>
				<xs:sequence>
					<xs:element name="origin" type="xs:string" maxOccurs="unbounded"/>
					<xs:choice maxOccurs="1" minOccurs="0">
						<xs:element name="precio" type="xs:int"/>
						<xs:element name="price" type="xs:int"/>
					</xs:choice>
				</xs:sequence>
				<xs:attribute name="id" type="xs:ID" use="required"/>
				</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== joseluissol/cursoJava/XML/src/es/coritel/java/xsd/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="products.xsd">
	<product id="A191">
		<origin>Madrid</origin>
		<precio>100</precio>
	</product>
	<product id="A167">
		<origin>Paris</origin>
		<precio>150</precio>
	</product>
	<product id="A180">
		<origin>Tokyo</origin>
		<price>200</price>
	</product>
</products>
