=== joseluissol/cursoJava/XML/src/es/coritel/java/dtd/Ex1.dtd
<!ELEMENT proveedores (proveedor+)>
<!ELEMENT proveedor (nombre, productos, telefono*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT productos (producto+)>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

=== joseluissol/cursoJava/XML/src/es/coritel/java/dtd/Ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proveedores SYSTEM "Ex1.dtd">
<proveedores>
	<proveedor>
		<nombre>Pascal</nombre>
		<productos>
			<producto>Leche</producto>
			<producto>Flan</producto>
		</productos>
	</proveedor>
	<proveedor>
		<nombre>Capit√°n Pesconovo</nombre>
		<productos>
			<producto>Merluza</producto>
		</productos>
		<telefono>
			952888777
		</telefono>
	</proveedor>
</proveedores>
