=== joseluissol/cursoJava/XML/src/es/coritel/java/dtd/Ex2.dtd
<!ENTITY empresa "Empresa">
<!ELEMENT almacen (productos)>
<!ATTLIST almacen empresa CDATA #REQUIRED>
<!ELEMENT productos (producto+)>
<!ATTLIST producto id ID #REQUIRED
					nohay CDATA #IMPLIED>
<!ELEMENT producto (nombre, precio, caracteristicas?)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST precio valor CDATA #REQUIRED
				moneda CDATA #REQUIRED>
<!ELEMENT precio EMPTY>
<!ELEMENT caracteristicas (#PCDATA)>

=== joseluissol/cursoJava/XML/src/es/coritel/java/dtd/Ex2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE almacen SYSTEM "Ex2.dtd">
<almacen empresa="&empresa;">
   <productos>
      <producto id="A191">
         <nombre>Teclado</nombre>
         <precio valor="20" moneda="euros"/>
         <caracteristicas>15 pulgadas</caracteristicas>
      </producto>
      <producto id="A167">
         <nombre>Monitor 14'</nombre>
         <precio valor="20000" moneda="pesetas"/>
      </producto>
      <producto id="A180" nohay="A167">
         <nombre>Monitor 15'</nombre>
         <precio valor="20000" moneda="pesetas"/>
      </producto>
   </productos>
</almacen>
